language: csharp
solution: GlobalX.NameSorter.sln

install:
  - nuget restore GlobalX.NameSorter.sln
  - nuget Install xunit.runner.console -Version 2.4.1  -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release GlobalX.NameSorter.sln
  - mono ./testrunner/xunit.runner.console/2.4.1/tools/net452/xunit.console.exe ./GlobalX.NameSorter.UnitTest/bin/Release/netcoreapp3.1/UnitTest.dll
